<a href="https://colab.research.google.com/github/RHarishk/diabetes-survey-analysis/blob/main/Diabetes_survey_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/diabetes_prediction_dataset.csv")

In [ ]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [ ]:
df[df["diabetes"]==1]["gender"].value_counts()

gender
Female    4461
Male      4039
Name: count, dtype: int64

In [ ]:
#task2  how many of the men and women have blood glucsoe level more than 200,
#have smoking habit and smoking history,have hypertension,have heart disease and
# he/she should not have diabetese
df[(df["blood_glucose_level"]>=200) & (df["smoking_history"].isin(["current","former","ever","not current"])) & (df["hypertension"]==1) & (df["heart_disease"]==1) &(df["diabetes"]==0)].value_counts("gender")

gender
Male      12
Female     5
Name: count, dtype: int64

In [ ]:
#task3  along with task 2 add age below 14 and perform how many male and female are in diabetes
df[(df["blood_glucose_level"]>=200) & (df["smoking_history"].isin(["current","former","ever","not current"])) &
(df["hypertension"]==1) & (df["heart_disease"]==1) &(df["diabetes"]==1) & (df["age"]<=14)].value_counts("gender")

Series([], Name: count, dtype: int64)

In [ ]:
#task4  how many mele and female have perfect bmi, glucose < 180 ,no smoking habit,no bp,no hd and age > 40
df[(df["bmi"].between(18.5,24.9))&(df["blood_glucose_level"] < 180) & (df["smoking_history"]=="never")& (df["hypertension"]==0)&(df["heart_disease"]==0) & (df["age"]>40)].value_counts("gender")

gender
Female    2344
Male       571
Name: count, dtype: int64

In [ ]:
#task5 lean or obese and hbaic<6 from all these kids(<12), and teenager(12-18) and adult(18)

def age_group(age):
  if age < 13:
    return "Child"
  elif age > 12 and age < 20:
    return "Teenager"
  else:
    return "Elder"


df["age_catagory"] = df["age"].apply(age_group)

In [ ]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,bmi_category,age_catagory
0,Female,80.0,0,1,never,25.19,6.6,140,0,Overweight,Elder
1,Female,54.0,0,0,No Info,27.32,6.6,80,0,Overweight,Elder
2,Male,28.0,0,0,never,27.32,5.7,158,0,Overweight,Elder
3,Female,36.0,0,0,current,23.45,5.0,155,0,Normal,Elder
4,Male,76.0,1,1,current,20.14,4.8,155,0,Normal,Elder

In [ ]:
def bmi_category(bmi):
  if bmi < 18.5:
    return "Underweight"
  elif 18.5 <= bmi < 25:
    return "Normal"
  elif 25 <= bmi < 30:
    return "Overweight"
  else:
    return "Obese"

df['bmi_category'] = df['bmi'].apply(bmi_category)

In [ ]:
df.drop("age_catagory",axis=1,inplace=True)

In [ ]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,bmi_category,age_catagory
0,Female,80.0,0,1,never,25.19,6.6,140,0,Overweight,Elder
1,Female,54.0,0,0,No Info,27.32,6.6,80,0,Overweight,Elder
2,Male,28.0,0,0,never,27.32,5.7,158,0,Overweight,Elder
3,Female,36.0,0,0,current,23.45,5.0,155,0,Normal,Elder
4,Male,76.0,1,1,current,20.14,4.8,155,0,Normal,Elder
...,...,...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0,Overweight,Elder
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0,Underweight,Child
99997,Male,66.0,0,0,former,27.83,5.7,155,0,Overweight,Elder
99998,Female,24.0,0,0,never,35.42,4.0,100,0,Obese,Elder
99999,Female,57.0,0,0,current,22.43,6.6,90,0,Normal,Elder

In [ ]:
df[(df["bmi_category"].isin(["Underweight","Obese"]))& (df["HbA1c_level"]<6)].groupby(["gender", "age_catagory", "bmi_category"])['bmi_category'].value_counts()

gender  age_catagory  bmi_category
Female  Child         Obese             53
                      Underweight     1937
        Elder         Obese           7084
                      Underweight      423
        Teenager      Obese            252
                      Underweight      168
Male    Child         Obese             57
                      Underweight     2035
        Elder         Obese           4371
                      Underweight      117
        Teenager      Obese            208
                      Underweight      191
Other   Child         Underweight        1
        Elder         Obese              1
Name: count, dtype: int64